#!/user/bin/env python

from pyspark.sql.types import *

myschema = StructType([
	StructField("Summons Number", StringType(), True),
	StructField("Plate ID", StringType(), True), 
	StructField("Registration State", StringType(), True), 
	StructField("Plate Type", StringType(), True), 
	StructField("Issue Date", StringType(), True),
	StructField("Violation Code", StringType(), True), 
	StructField("Vehicle Body Type", StringType(), True), 
	StructField("Vehicle Make", StringType(), True),
	StructField("Issuing Agency", StringType(), True),
	StructField("Street Code1", StringType(), True),	
	StructField("Street Code2", StringType(), True),	
	StructField("Street Code3", StringType(), True),	
	StructField("Vehicle Expiration Date", StringType(), True),
	StructField("Violation Location", StringType(), True),	
	StructField("Violation Precinct", StringType(), True),
	StructField("Issuer Precinct", StringType(), True),
	StructField("Issuer Code", StringType(), True),
	StructField("Issuer Command", StringType(), True),
	StructField("Issuer Squad", StringType(), True),
	StructField("Violation Time", StringType(), True),
	StructField("Time First Observed", StringType(), True),
	StructField("Violation County", StringType(), True),
	StructField("Violation In Front Of Or Opposite", StringType(), True),
	StructField("House Number", StringType(), True),
	StructField("Street Name", StringType(), True),
	StructField("Intersecting Street", StringType(), True),
	StructField("Date First Observed", StringType(), True),
	StructField("Law Section", StringType(), True),
	StructField("Sub Division", StringType(), True),
	StructField("Violation Legal Code", StringType(), True),
	StructField("Days Parking In Effect", StringType(), True),
	StructField("From Hours In Effect", StringType(), True),
	StructField("To Hours In Effect", StringType(), True),
	StructField("Vehicle Color", StringType(), True),
	StructField("Unregistered Vehicle?", StringType(), True),
	StructField("Vehicle Year", StringType(), True),
	StructField("Meter Number", StringType(), True),
	StructField("Feet From Curb", StringType(), True),
	StructField("Violation Post Code", StringType(), True),
	StructField("Violation Description", StringType(), True),
	StructField("No Standing or Stopping Violation", StringType(), True),
	StructField("Hydrant Violation", StringType(), True),
	StructField("Double Parking Violation", StringType(), True),
	StructField("Latitude", StringType(), True),
	StructField("Longitude", StringType(), True),
	StructField("Community Board", StringType(), True),
	StructField("Community Council", StringType(), True),
	StructField("Census Tract", StringType(), True),
	StructField("BIN", StringType(), True),
	StructField("BBL", StringType(), True),
	StructField("NTA", StringType(), True)])